### ISSUE TITLE
i have a little question

### ISSUE THREAD

**Issue by MRHERT** [ChandlerMcCowan/8BitWiFiVisualizer#1]
can we use a signal 2.4GHZ amplifier for the esp8266 in order to increase the range oF IT ?

**Comment by ChandlerMcCowan** [comment]
Unfortunately I don't think so. The ESP8266 has a PCB trace antenna. That means the antenna (and the RF Signals transmitted and received) are being routed through a specially designed copper trace on the module itself.

[View more about trace antennas ](https://en.wikipedia.org/wiki/Microstrip_antenna)

to externally amplify the signal would also risk entering into the territory of improperly operating radio equipment, which depending on where you are might be more off limits than others. 

To even access the RF signals would mean accessing that trace antenna and attempting to solder onto a connector. There are a few ESP modules that have a u.fl connector. That would make it much easier to access the RF signals, but I don't think it would work since the RF communication is bi-directional (transmitting and receiving). 

I believe the ESP8266 has options in firmware to adjust the transmitting power. But to increase it's reception is really to increase the transmitting power of the signals you are looking for. Otherwise you would be improving the ability for the device to pick up and understand weaker signals, something I don't think is worth trying to make happen with an ESP8266.

Another strategy is to use a special antenna that directs energy into a more concentrated area in 3d space, so it is more powerful in that direction. Some are shaped like cones, and others donuts.

[Learn more about radiation patterns](https://en.wikipedia.org/wiki/Radiation_pattern)

Let me know if you have other questions, happy to help. 

I will close this issue, but don't hesitate to open a new one!
